CREATE TABLE [dbo].[Tenant]
(
	[ID] BIGINT IDENTITY(911,1) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Subdomain] NVARCHAR(20) NOT NULL,
	[CreatedDateTime] DATETIME2(7) NOT NULL,
	[CreatedByAccount] NVARCHAR(500) NOT NULL,
	[ChangeTimestamp] ROWVERSION NOT NULL,
	CONSTRAINT [PK_Tenant] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [UQ_Tenant_SubDomain] UNIQUE NONCLUSTERED ([Subdomain] ASC)
)
GO
